### PR TITLE
Fixed Noisy ArgmentError

### PR DESCRIPTION
**Pull request by InfectedDuck**
I was kinda annoyed by the ArgumentError message when no args were specified.
So i changed it a bit although i'm new to ruby.

### CODE REVIEW

**Comment by acrogenesis** [comment]
You are right @InfectedDuck, but we should also provide an error message, telling what they missed. So perhaps the best option is to `rescue` the `ArgumentError`, print the Error and the `--help`. We should also change the `ArgumentError` with `OptionParser::MissingArgument`. Also [line 5](https://github.com/acrogenesis/macchanger/pull/3/files#diff-bc69dbd5c837abcd99143423914b5fe6R5) is unnecessary (the comment). 

Do you want to do this fixes, or should I do them.

**Comment by InfectedDuck** [comment]
Thanks for the feedback i’m totally new to this open-source world …
I would appreciate if you do the fixes, since i’m totally a novice in ruby
thanks

**Comment by mmathys** [comment]
thanks for this, @acrogenesis! :+1:

**Comment by acrogenesis** [comment]
@InfectedDuck you can see the solution I came up with at 04cb843

**Comment by InfectedDuck** [comment]
Thanks for the help

**Pull request closed without merging**
